In [3]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [4]:
import numpy as np
np.__version__

'1.26.2'

In [5]:
m3 = np.arange(1,11)
m3

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [6]:
np.insert(m3, 0, 100)

array([100,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10])

In [7]:
m3[-1]

10

In [12]:
np.insert?

Signature:       np.insert(arr, obj, values, axis=None)
Call signature:  np.insert(*args, **kwargs)
Type:            _ArrayFunctionDispatcher
String form:     <function insert at 0x1079298a0>
File:            /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/numpy/lib/function_base.py
Docstring:      
Insert values along the given axis before the given indices.

Parameters
----------
arr : array_like
    Input array.
obj : int, slice or sequence of ints
    Object that defines the index or indices before which `values` is
    inserted.

    .. versionadded:: 1.8.0

    Support for multiple insertions when `obj` is a single scalar or a
    sequence with one element (similar to calling insert multiple
    times).
values : array_like
    Values to insert into `arr`. If the type of `values` is different
    from that of `arr`, `values` is converted to the type of `arr`.
    `values` should be shaped so that ``arr[...,obj,...] = values``
    is legal.
axis : in

In [13]:
np.insert(m3, -1, 500)  # 인덱싱/슬라이싱 end처럼 인식


array([  1,   2,   3,   4,   5,   6,   7,   8,   9, 500,  10])

In [14]:
np.insert(m3, len(m3), 500) 


array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10, 500])

In [15]:
m4 = np.arange(1,10).reshape(3,3)
m4

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [16]:
np.insert(m4, 0, 100) # 2차원배열의 경우 axis 미설정시 1차원으로 변경되어 삽입


array([100,   1,   2,   3,   4,   5,   6,   7,   8,   9])

In [17]:
# 1열으로 [100,100,100] 삽입
np.insert(m4, 0, 100, axis=1)

array([[100,   1,   2,   3],
       [100,   4,   5,   6],
       [100,   7,   8,   9]])

In [18]:
# 리스트로 삽입
np.insert(m4, 0, [100,200,300], axis=1)

array([[100,   1,   2,   3],
       [200,   4,   5,   6],
       [300,   7,   8,   9]])

In [19]:
m4.shape, m4.shape[1], len(m4)


((3, 3), 3, 3)

In [20]:
# 마지막 컬럼으로 삽입
# 배열명.shape[1] 칼럼 길이
np.insert(m4, m4.shape[1], [100,200,300], axis=1)

array([[  1,   2,   3, 100],
       [  4,   5,   6, 200],
       [  7,   8,   9, 300]])

In [21]:
# 마지막 행에 삽입
np.insert(m4, m4.shape[0], [100,200,300], axis=0)

array([[  1,   2,   3],
       [  4,   5,   6],
       [  7,   8,   9],
       [100, 200, 300]])

In [22]:
m4


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [23]:
np.delete(m4, 0, axis=0)


array([[4, 5, 6],
       [7, 8, 9]])

In [24]:
a = np.array([1,2,3])
b = np.array([4,5,6])
np.vstack((a,b))

array([[1, 2, 3],
       [4, 5, 6]])

In [25]:
np.hstack((a,b))

array([1, 2, 3, 4, 5, 6])

In [26]:
c = np.array([[1,2,3]]) # 2차원
c, c.ndim, c.shape

(array([[1, 2, 3]]), 2, (1, 3))

In [27]:
d = np.array([[4,5,6]]) # 2차원
d, d.ndim, d.shape

(array([[4, 5, 6]]), 2, (1, 3))

In [28]:
f = np.concatenate((c,d), axis=0) #
f, f.ndim, f.shape

(array([[1, 2, 3],
        [4, 5, 6]]),
 2,
 (2, 3))

In [29]:
f = np.concatenate((c,d), axis=1) #
f, f.ndim, f.shape

(array([[1, 2, 3, 4, 5, 6]]), 2, (1, 6))

In [30]:
matrix = np.arange(1, 21)
matrix

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [31]:
matrix > 10

array([False, False, False, False, False, False, False, False, False,
       False,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True])

In [32]:
matrix[matrix > 10]


array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [33]:
(matrix > 10).sum()


10

In [34]:
num = np.random.randint(1,100,30)
(num > 30) & (num < 70)

array([ True,  True, False, False,  True, False, False, False, False,
       False,  True,  True,  True,  True, False, False, False, False,
        True, False,  True,  True, False, False, False,  True, False,
        True,  True, False])

In [35]:
num = np.random.randint(1,100,30)
num, num[(num > 30) & (num < 70)]

(array([62, 93, 16, 68, 60, 50, 26, 63, 27, 91, 44, 29, 37, 68, 41, 78, 82,
        31, 35, 40, 66, 98, 45, 42, 76, 15, 54, 37, 78, 98]),
 array([62, 68, 60, 50, 63, 44, 37, 68, 41, 31, 35, 40, 66, 45, 42, 54, 37]))

In [36]:
# ~ 은 reverse를 의미
num[~(num > 30) & (num < 70)]

array([16, 26, 27, 29, 15])

In [37]:
# 10보다 작거나 90보다 큰 수,
num[(num < 10) | (num > 90)]

array([93, 91, 98, 98])

In [38]:
 num[~(num < 10) | (num > 90)]


array([62, 93, 16, 68, 60, 50, 26, 63, 27, 91, 44, 29, 37, 68, 41, 78, 82,
       31, 35, 40, 66, 98, 45, 42, 76, 15, 54, 37, 78, 98])